# Site settings
title: My Coding Journey
header-img: img/home-bg.png
email: wmthmps1@gmail.com
copyright_name: Wmthmps1
description: > # this means to ignore newlines until "baseurl:"
  From Beginner to Professional
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Wmthmps1
learn_profile: Wmthmps1
email_username: wmthmps1@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
